apiVersion: v1
kind: Service
metadata:
  name: game-hub-service
spec:
  selector:
    app: game-hub  
  ports:
    - protocol: TCP
      port: 80  # Exposed port for external traffic
      targetPort: 5173  # Port inside the container
  type: LoadBalancer 
