name: CI/CD for Game Hub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set up Docker Buildx
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 4. Build and push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/game-hub:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/game-hub:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/game-hub:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/game-hub:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/game-hub:cache,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Install Minikube
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      # 2. Start Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          chown -R $USER $HOME/.minikube/

      # 3. Configure kubectl for Minikube
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          chown -R $USER $HOME/.kube
          chown -R $USER $HOME/.minikube
          export KUBECONFIG=~$HOME/.kube/config

      # 4. Verify Kubernetes Cluster
      - name: Verify Cluster Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      # 5. Set up Helm
      - name: Set up Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      # 6. Deploy with Helm
      - name: Deploy with Helm
        run: helm upgrade --install game-hub ./my-game-hub --set image.repository=${{ secrets.DOCKER_USERNAME }}/game-hub,image.tag=${{ github.sha }}
